servibook_proj/servibook_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions

from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Silant_API",
        default_version='v1',
        description="Документация API",
    ),
    public=True,
    permission_classes=[permissions.AllowAny, ],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('silant_servibook.urls')),
    path('accounts/', include('allauth.urls')),
    path('swagger-ui/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

servibook_proj/silant_servibook/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin


class Machinery(models.Model):
    objects = None
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Модель техники", verbose_name="Описание")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Модель техники"
        verbose_name_plural = "Модель техники"


class Engine(models.Model):
    objects = None
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Модель двигателя", verbose_name="Описание")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Модель двигателя"
        verbose_name_plural = "Модель двигателей"


class Transmission(models.Model):
    objects = None
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Модель трансмиссии", verbose_name="Описание")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Модель трансмиссии"
        verbose_name_plural = "Модель трансмиссий"


class DriveAxle(models.Model):
    objects = None
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Модель ведущего моста", verbose_name="Описание")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Модель ведущего моста"
        verbose_name_plural = "Модель ведущих мостов"


class SteerAxle(models.Model):
    objects = None
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Модель управляемого моста", verbose_name="Описание")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Модель управляемого моста"
        verbose_name_plural = "Модель управляемых мостов"


class ServiceDepartment(models.Model):
    objects = None
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Сервисная компания", verbose_name="Описание")
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь", blank=True, null=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Сервисная компания"
        verbose_name_plural = "Сервисные компании"


class ServiceDepInOperation(models.Model):
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Организация, проводившая ТО", verbose_name="Описание")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Организация, проводившая ТО"
        verbose_name_plural = "Организации, проводившие ТО"


class MaintenanceType(models.Model):
    objects = None
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Вид ТО", verbose_name="Описание")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Вид ТО"
        verbose_name_plural = "Виды ТО"


class FailureUnit(models.Model):
    objects = None
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Узел отказа", verbose_name="Описание")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Узел отказа"
        verbose_name_plural = "Узлы отказа"


class RepairProcedure(models.Model):
    objects = None
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Способ восстановления", verbose_name="Описание")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Способ восстановления"
        verbose_name_plural = "Способы восстановления"


class Client(models.Model):
    objects = None
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(max_length=255, default="Клиент", verbose_name="Описание")
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Vehicle(models.Model):
    objects = None
    vehicle_model = models.ForeignKey(Machinery, on_delete=models.CASCADE, verbose_name="Модель техники",
                                      related_name="vehicle_machinery")
    vehicle_number = models.CharField(unique=True, max_length=255, verbose_name="Заводской № машины")
    engine_model = models.ForeignKey(Engine, on_delete=models.CASCADE, verbose_name="Модель двигателя",
                                     related_name="vehicle_engine")
    engine_number = models.CharField(unique=True, max_length=255, verbose_name="Заводской № двигателя")
    transmission_model = models.ForeignKey(Transmission, on_delete=models.CASCADE, verbose_name="Модель трансмиссии")
    transmission_number = models.CharField(unique=True, max_length=255, verbose_name="Заводской № трансмиссии")
    drive_axle_model = models.ForeignKey(DriveAxle, on_delete=models.CASCADE, verbose_name="Модель ведущего моста")
    drive_axle_number = models.CharField(max_length=255, verbose_name="Заводской № ведущего моста")
    steer_axle_model = models.ForeignKey(SteerAxle, on_delete=models.CASCADE, verbose_name="Модель управляемого моста")
    steer_axle_number = models.CharField(max_length=255, verbose_name="Заводской № управляемого моста")
    delivery_contract = models.CharField(max_length=255, verbose_name="Договор поставки (№, дата)")
    shipment_date = models.DateField(max_length=50, verbose_name="Дата отгрузки с завода")
    customer = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name="Покупатель")
    end_user = models.CharField(max_length=255, verbose_name="Грузополучатель (конечный потребитель)")
    shipping_address = models.CharField(max_length=255, verbose_name="Адрес поставки (эксплуатации)")
    configuration = models.TextField(max_length=1000, default="Стандарт", verbose_name="Комплектация (доп. опции)")
    service_department = models.ForeignKey(ServiceDepartment, on_delete=models.CASCADE,
                                           verbose_name="Сервисная компания")

    def __str__(self):
        return f'{self.vehicle_number}'

    class Meta:
        verbose_name = "Машина"
        verbose_name_plural = "Машины"


class Maintenance(models.Model):
    objects = None
    type = models.ForeignKey(MaintenanceType, on_delete=models.CASCADE, verbose_name="Вид ТО")
    maintenance_date = models.DateField(max_length=50, verbose_name="Дата проведения ТО")
    operating_time = models.IntegerField(default=0, verbose_name="Наработка, м/час")
    order_number = models.CharField(max_length=255, verbose_name="Номер заказ-наряда")
    order_date = models.DateField(max_length=50, verbose_name="Дата заказ-наряда")
    maintenance_service = models.ForeignKey(ServiceDepInOperation, on_delete=models.CASCADE,
                                            verbose_name="Организация, проводившая ТО")
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, verbose_name="Машина")
    service_department = models.ForeignKey(ServiceDepartment, on_delete=models.CASCADE,
                                           verbose_name="Сервисная компания")

    def save(self, *args, **kwargs):
        self.service_department = self.vehicle.service_department
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.vehicle} - {self.type} - {self.maintenance_date}'

    class Meta:
        verbose_name = "Техническое обслуживание"
        verbose_name_plural = "Технические обслуживания"


class Reclamation(models.Model):
    objects = None
    failure_date = models.DateField(verbose_name="Дата отказа")
    operating_time = models.IntegerField(default=0, verbose_name="Наработка, м/час")
    failure_unit = models.ForeignKey(FailureUnit, on_delete=models.CASCADE, verbose_name="Узел отказа")
    failure_description = models.TextField(max_length=1000, verbose_name="Описание отказа")
    repair_procedure = models.ForeignKey(RepairProcedure, on_delete=models.CASCADE,
                                         verbose_name="Способ восстановления")
    spare_parts = models.TextField(max_length=1000, blank=True, verbose_name="Используемые запасные части")
    repair_date = models.DateField(max_length=50, verbose_name="Дата восстановления")
    nonuse_time = models.IntegerField(default=0, verbose_name="Время простоя техники")
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE, verbose_name="Машина")
    service_department = models.ForeignKey(ServiceDepartment, on_delete=models.CASCADE,
                                           verbose_name="Сервисная компания")

    def save(self, *args, **kwargs):
        self.nonuse_time = (self.repair_date - self.failure_date).days
        self.service_department = self.vehicle.service_department
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.vehicle} - {self.failure_date} - {self.failure_unit}'

    class Meta:
        verbose_name = "Рекламация"
        verbose_name_plural = "Рекламации"


class MaintenanceAdmin(admin.ModelAdmin):
    exclude = ["service_department"]


class ReclamationAdmin(admin.ModelAdmin):

servibook_proj/templates/maintenance.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Техническое обслуживание
{% endblock title %}

{% block content %}
<section id="title">
    <div class="row justify-content-center align-items-center">
        <h3 class="col-sm text-center">Информация о проведенных ТО вашей техники</h3>
    </div>
</section>

<section id="edit_options">
    <div class="row justify-content-center align-items-center">
        {% if perms.silant_servibook.change_maintenance %}
        <div class="col-6 col-sm-2 text-center">
            <a class="inactive_tab" href="/maintenances/{{ maintenance.pk }}/update/">Редактировать</a>
        </div>
        {% endif %}
        {% if perms.silant_servibook.delete_maintenance %}
        <div class="col-6 col-sm-2 text-center">
            <a class="inactive_tab" href="/maintenances/{{ maintenance.pk }}/delete/">Удалить</a>
        </div>
        {% endif %}
    </div>
</section>

<section class="mx-auto w-auto my-1 text-start">
    <div class="table-responsive-sm justify-content-center align-items-center my-2">
        <table class="table table-sm table-striped p-5">
            <thead>
                <tr>
                    <th>Параметр</th>
                    <th>Значение</th>
                    <th>Описание</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Зав. № машины</td>
                    <td><a href="{% url 'vehicle_detail' maintenance.vehicle.pk %}">{{ maintenance.vehicle }}</a></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Вид ТО</td>
                    <td>
                        <a href="{% url 'maintenance_type_detail' maintenance.type.pk %}">{{ maintenance.type }}</a>
                    </td>
                    <td>{{ maintenance.type.description }}</td>
                </tr>
                <tr>
                    <td>Дата проведения ТО</td>
                    <td>{{ maintenance.maintenance_date|date:'d.m.Y' }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Наработка, м/час</td>
                    <td>{{ maintenance.operating_time }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Номер заказ-наряда</td>
                    <td>{{ maintenance.order_number }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Дата заказ-наряда</td>
                    <td>{{ maintenance.order_date|date:'d.m.Y' }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Организация, проводившая ТО</td>
                    <td>{{ maintenance.maintenance_service }}</td>
                    <td>{{ maintenance.maintenance_service.description }}</td>
                </tr>
                <tr>
                    <td>Сервисная компания</td>
                    <td>
                        <a href="{% url 'service_department_detail' maintenance.service_department.pk %}">
                        {{ maintenance.service_department }}</a>
                    </td>
                    <td>{{ maintenance.service_department.description }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="backButton">
        <a class="button" href="/maintenances/">
            <button class="btn" style="background-color: #1d70b7; color: #ffffff">Назад</button>
        </a>
    </div>
</section>
{% endblock content %}

servibook_proj/templates/maintenances.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}

{% block title %}
    "Мой Силант" - Техническое обслуживание
{% endblock title %}

{% block content %}
<section id="title">
    {% if request.user.is_authenticated %}
        <div class="row">
            <h3 class="col-sm text-center">Техническое обслуживание</h3>
        </div>
    {% endif %}
</section>

<section id="nav_links" class="mx-auto w-auto">
    <div class="table-responsive-md justify-content-center align-items-center my-2">
        <table class="table table-sm table-hover border-bottom border-dark border-3 mb-4 align-middle">
            <thead>
              <tr>
                {% if request.user.is_authenticated %}
                <th class="text-center">
                  <img width="40px" height="35px" src="/static/images/vehicles.png" alt="Машины">
                  <a href="/">Машины</a>
                </th>
                {% endif %}
                {% if request.user.is_authenticated %}
                <th class="text-center">
                  <img width="40px" height="35px" src="/static/images/maintenance.jpg" alt="ТО">
                  <a href="/maintenances">Техническое обслуживание</a>
                </th>
                {% endif %}
                {% if request.user.is_authenticated %}
                <th class="text-center">
                  <img width="40px" height="35px" src="/static/images/claim.jpg" alt="Рекламации">
                  <a href="/reclamations">Рекламации</a>
                </th>
                {% endif %}
                {% if perms.silant_servibook.add_maintenance %}
                <th class="text-center">
                    <img width="40px" height="35px" src="/static/images/note.jpg" alt="Запись о ТО">
                    <a href="/maintenances/create/">Добавить запись о ТО</a>
                </th>
                {% endif %}
              </tr>
            </thead>
        </table>
    </div>
</section>

<section id="search_tabs">
    <div class="formWrapper">
      <form class="form form-control" style="background-color: #D20A11;">
        <div class="d-sm-flex text-center justify-content-evenly align-items-center my-2 text-white">
            {{ filter_set.form }}
          <input class="btn btn-primary" type="submit" value="Поиск"/>
        </div>
      </form>
    </div>
</section>

<section id="maintenances_table" class="mt-2 mx-auto w-auto" style="font-size: 14px;">
    <div class="table-responsive-md justify-content-center my-2">
        {% if maintenances %}
         <table class="table table-sm table-bordered border-light align-middle my-1">
            <thead>
                <tr class="table_header text-center text-white align-middle" style="background-color: #163e6c">
                    <th>Дата проведения ТО</th>
                    <th>Зав. № машины</th>
                    <th>Вид ТО</th>
                    <th>Наработка, м/час</th>
                    <th>Номер заказ-наряда</th>
                    <th>Дата заказ-наряда</th>
                    <th>Организация, проводившая ТО</th>
                    <th>Сервисная компания</th>
                </tr>
            </thead>
            <tbody>
                {% for maintenance in maintenances %}
                <tr class="table_body text-center" style="background-color: whitesmoke">
                  <td>
                    <a href="{% url 'maintenance_detail' maintenance.pk %}">
                        {{ maintenance.maintenance_date|date:'d.m.Y' }}
                    </a>
                  </td>
                  <td><a href="{% url 'vehicle_detail' maintenance.vehicle.pk %}">{{ maintenance.vehicle }}</a></td>
                  <td><a href="{% url 'maintenance_type_detail' maintenance.type.pk %}">{{ maintenance.type }}</a></td>
                  <td>{{ maintenance.operating_time }}</td>
                  <td>{{ maintenance.order_number }}</td>
                  <td>{{ maintenance.order_date|date:'d.m.Y' }}</td>
                  <td>
                    <a href="{% url 'maintenance_detail' maintenance.maintenance_service.pk %}">
                        {{ maintenance.maintenance_service }}
                    </a>
                  </td>
                  <td>
                    <a href="{% url 'service_department_detail' maintenance.service_department.pk %}">
                        {{ maintenance.service_department }}
                    </a>
                  </td>
                </tr>
                {% endfor %}
            </tbody>
         </table>
    </div>
</section>
{% else %}
<div class="row">
    <h2 class="col-sm text-center">ТО с такими параметрами в базе данных не найдено!</h2>
</div>
{% endif %}

<section id="pagination" class="mt-2">
    {% if page_obj.has_other_pages %}
    <p class="text-center">
        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
    </p>
    <nav aria-label="Навигация по страницам таблицы">
        <ul class="pagination justify-content-center mt-2">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true">&lsaquo;</span></a>
            </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active" aria-current="page"><span class="page-link">{{ num }}</span>
                    </li>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><span
                        aria-hidden="true">&rsaquo;</span></a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</section>
{% endblock content %}

servibook_proj/templates/reclamation.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Рекламация
{% endblock title %}

{% block content %}
<section id="title">
    <div class="row justify-content-center align-items-center">
        <h3 class="col-sm text-center">Информация о рекламации к технике</h3>
    </div>
</section>

<section id="edit_options">
    <div class="row justify-content-center align-items-center">
        {% if perms.silant_servibook.change_reclamation %}
        <div class="col-6 col-sm-2 text-center">
            <a class="inactive_tab" href="/reclamations/{{ reclamation.pk }}/update/">
                Редактировать
            </a>
        </div>
        {% endif %}
        {% if perms.silant_servibook.delete_reclamation %}
        <div class="col-6 col-sm-2 text-center">
            <a class="inactive_tab" href="/reclamations/{{ reclamation.pk }}/delete/">
                Удалить
            </a>
        </div>
        {% endif %}
    </div>
</section>

<section class="mx-auto w-auto my-1 text-start">
    <div class="table-responsive-sm justify-content-center align-items-center my-2">
        <table class="table table-sm table-striped p-5">
            <thead>
                <tr>
                    <th>Параметр</th>
                    <th>Значение</th>
                    <th>Описание</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Зав. № машины</td>
                    <td><a href="{% url 'vehicle_detail' reclamation.vehicle.pk %}">{{ reclamation.vehicle }}</a></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Дата отказа</td>
                    <td>{{ reclamation.failure_date|date:'d.m.Y' }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Наработка, м/час</td>
                    <td>{{ reclamation.operating_time }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Узел отказа</td>
                    <td><a href="{% url 'failure_unit_detail' reclamation.failure_unit.pk %}">
                        {{ reclamation.failure_unit }}
                        </a>
                    </td>
                    <td>{{ reclamation.failure_unit.description }}</td>
                </tr>
                <tr>
                    <td>Описание отказа</td>
                    <td>{{ reclamation.failure_description }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Способ восстановления</td>
                    <td>
                        <a href="{% url 'repair_procedure_detail' reclamation.repair_procedure.pk %}">
                                {{ reclamation.repair_procedure }}
                        </a>
                    </td>
                    <td>{{ reclamation.repair_procedure.description }}</td>
                </tr>
                <tr>
                    <td>Используемые запасные части</td>
                    <td>{{ reclamation.spare_parts }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Дата восстановления</td>
                    <td>{{ reclamation.repair_date|date:'d.m.Y' }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Время простоя, дни</td>
                    <td>{{ reclamation.nonuse_time }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Сервисная компания</td>
                    <td>
                        <a href="{% url 'service_department_detail' reclamation.service_department.pk %}">
                            {{ reclamation.service_department }}
                        </a>
                    </td>
                    <td>{{ reclamation.service_department.description }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="div_button">
        <a class="a_button" href="/reclamations/">
            <button class="btn" style="background-color: #1d70b7; color: #ffffff">Назад</button>
        </a>
    </div>
</section>
{% endblock content %}

servibook_proj/templates/vehicle.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Машина
{% endblock title %}

{% block content %}
<section id="title">
    <div class="row justify-content-center align-items-center">
        <h3 class="col-sm text-center">Информация о машине</h3>
    </div>
</section>

<section id="edit_options">
    <div class="row justify-content-center align-items-center">
        {% if perms.silant_servibook.change_vehicle %}
        <div class="col-6 col-sm-2 text-center">
            <a class="inactive_tab" href="/vehicles/{{ vehicle.pk }}/update/">
                Редактировать
            </a>
        </div>
        {% endif %}
        {% if perms.silant_servibook.delete_vehicle %}
        <div class="col-6 col-sm-2 text-center">
            <a class="inactive_tab" href="/vehicles/{{ vehicle.pk }}/delete/">
                Удалить
            </a>
        </div>
        {% endif %}
    </div>
</section>

<section class="mx-auto w-auto my-1 text-start">
    <div class="table-responsive-sm justify-content-center align-items-center my-2">
        <table class="table table-sm table-striped p-5">
            <thead>
                <tr>
                    <th>Параметр</th>
                    <th>Значение</th>
                    <th>Описание</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Зав. № машины</td>
                    <td>{{ vehicle.vehicle_number }}<td>
                    <td></td>
                </tr>
                <tr>
                    <td>Модель техники</td>
                    <td>
                        <a href="{% url 'machinery_detail' vehicle.vehicle_model.pk %}">{{ vehicle.vehicle_model }}</a>
                    </td>
                    <td>{{ vehicle.vehicle_model.description }}</td>
                </tr>
                <tr>
                    <td>Модель двигателя</td>
                    <td><a href="{% url 'engine_detail' vehicle.engine_model.pk %}">{{ vehicle.engine_model }}</a></td>
                    <td>{{ vehicle.engine_model.description }}</td>
                </tr>
                <tr>
                    <td>Зав. № двигателя</td>
                    <td>{{ vehicle.engine_number }}</td>
                </tr>
                <tr>
                    <td>Модель трансмиссии</td>
                    <td>
                        <a href="{% url 'transmission_detail' vehicle.transmission_model.pk %}">
                            {{ vehicle.transmission_model }}</a>
                    </td>
                    <td>{{ vehicle.transmission_model.description }}</td>
                </tr>
                <tr>
                    <td>Зав. № трансмиссии</td>
                    <td>{{ vehicle.transmission_number }}</td>
                </tr>
                <tr>
                    <td>Модель ведущего моста</td>
                    <td><a href="{% url 'drive_axle_detail' vehicle.drive_axle_model.pk %}">
                       {{ vehicle.drive_axle_model }}</a>
                    </td>
                    <td>{{ vehicle.drive_axle_model.description }}</td>
                </tr>
                <tr>
                    <td>Зав. № ведущего моста</td>
                    <td>{{ vehicle.drive_axle_number }}</td>
                </tr>
                <tr>
                    <td>Модель управляемого моста</td>
                    <td><a href="{% url 'steer_axle_detail' vehicle.steer_axle_model.pk %}">
                       {{ vehicle.steer_axle_model }}
                   </a></td>
                    <td>{{ vehicle.steer_axle_model.description }}</td>
                </tr>
                <tr>
                    <td>Зав. № управляемого моста</td>
                    <td>{{ vehicle.steer_axle_number }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Договор поставки</td>
                    <td>{{ vehicle.delivery_contract }}</td>
                    <td>{{ vehicle.delivery_contract.description }}</td>
                </tr>
                <tr>
                    <td>Дата отгрузки с завода</td>
                    <td>{{ vehicle.shipment_date|date:'d.m.Y' }}</td>
                </tr>
                <tr>
                    <td>Клиент</td>
                    <td><a href="{% url 'client_detail' vehicle.customer.pk %}">{{ vehicle.customer }}</a></td>
                    <td>{{ vehicle.customer.description }}</td>
                </tr>
                <tr>
                    <td>Конечный потребитель</td>
                    <td>{{ vehicle.end_user }}</td>
                </tr>
                <tr>
                    <td>Адрес поставки</td>
                    <td>{{ vehicle.shipping_address }}</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Комплектация</td>
                    <td>{{ vehicle.configuration|linebreaks }}</td>
                </tr>
                <tr>
                    <td>Сервисная компания</td>
                    <td><a href="{% url 'service_department_detail' vehicle.service_department.pk %}">
                       {{ vehicle.service_department }}
                   </a></td>
                    <td>{{ vehicle.service_department.description }}</td>
                </tr>
            </tbody>
        </table>
    </div>
     <div class="div_button">
         <a class="a_button" href="/">
             <button class="btn" style="background-color: #1d70b7; color: #ffffff">Назад</button>
         </a>
     </div>
</section>
{% endblock content %}